import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-analytics.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyCyb7Or-RejBGGJWO_uqXhdb_M1DVZOwXE",
  authDomain: "calidadxx.firebaseapp.com",
  projectId: "calidadxx",
  storageBucket: "calidadxx.firebasestorage.app",
  messagingSenderId: "747840831133",
  appId: "1:747840831133:web:42e3a6109388f1f5681e74",
  measurementId: "G-ZVQFZ250T2"
};

const app = initializeApp(firebaseConfig);
try { getAnalytics(app); } catch(e) {}
const auth = getAuth(app);
const db = getFirestore(app);
const $ = id => document.getElementById(id);

const BASE_COMPONENTS=[{"Componente":"Motor 1","Modelo":"Motor TV3-117BM","N° Serie":"7087882300209","Taller":"JSC BORYSFEN","Último Overhaul Fecha":"06/10/2023","TSO actual (h)":438.8,"Recurso asignado":1500,"Recurso restante":1061.2,"Tiempo de servicio":"10 años","Vencimiento Fecha":"06/10/2033","Estado":"OPERATIVO","Arranques TSO":null,"Recurso arranques":null,"Exceso arranques":null},{"Componente":"Motor 2","Modelo":"Motor TV3-117BM","N° Serie":"7087882200437","Taller":"JSC BORYSFEN","Último Overhaul Fecha":"06/10/2023","TSO actual (h)":438.8,"Recurso asignado":1500,"Recurso restante":1061.2,"Tiempo de servicio":"10 años","Vencimiento Fecha":"06/10/2033","Estado":"OPERATIVO","Arranques TSO":null,"Recurso arranques":null,"Exceso arranques":null},{"Componente":"Reductor Principal","Modelo":"Reductor VR-14","N° Serie":"25504360M","Taller":"CMR S.A.S.","Último Overhaul Fecha":"25/08/2023","TSO actual (h)":436.99,"Recurso asignado":1500,"Recurso restante":1063.01,"Tiempo de servicio":"10 años","Vencimiento Fecha":"25/08/2033","Estado":"OPERATIVO","Arranques TSO":null,"Recurso arranques":null,"Exceso arranques":null},{"Componente":"AI-9B","Modelo":"Motor de Arranque AI-9B","N° Serie":"7080924200355","Taller":"OOO ARP Motor","Último Overhaul Fecha":"16/07/2020","TSO actual (h)":62.83,"Recurso asignado":100,"Recurso restante":-94,"Tiempo de servicio":"8 años","Vencimiento Fecha":"16/07/2028","Estado":"OVERHAUL REQUERIDO","Arranques TSO":694,"Recurso arranques":600,"Exceso arranques":94}];
const DEFAULT_FLEET={"PNP-503":{modelo:"MI-17",numeroSerie:"",cola:"PNP-503",components:structuredClone(BASE_COMPONENTS)},"PNP-501":{modelo:"MI-17",numeroSerie:"",cola:"PNP-501",components:structuredClone(BASE_COMPONENTS).map(c=>({...c,"N° Serie":"",Taller:"","TSO actual (h)":0,"Recurso restante":0,Estado:"PENDIENTE"}))}};
const EDITABLE_FIELDS=["Componente","Modelo","N° Serie","TSO actual (h)","Recurso asignado","Recurso restante","Último Overhaul Fecha","Vencimiento Fecha","Taller","Tiempo de servicio","Arranques TSO","Recurso arranques"];
let FLEET=structuredClone(DEFAULT_FLEET), currentAircraft="PNP-503", mode="principales", currentUser=null, saveTimer=null;

function showMsg(text){ $('authMsg').textContent=text; $('authMsg').classList.remove('hidden'); }
function esc(s){return String(s??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[m]))}
function toNum(v){if(v===null||v===undefined||v==="")return 0;if(typeof v==="number")return v;const n=Number(String(v).replace(",","."));return Number.isFinite(n)?n:0}
function fmt(n,dec=1){if(n===null||n===undefined||n==="")return "—";if(typeof n==="number")return n.toLocaleString("es-PE",{maximumFractionDigits:dec,minimumFractionDigits:dec});return n}
function parseDateDMY(s){const m=String(s||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}
function daysUntil(s){const d=parseDateDMY(s);if(!d)return 999999;return Math.ceil((d-new Date())/(1000*60*60*24))}
function normalizeFleet(){for(const k of Object.keys(FLEET)){if(Array.isArray(FLEET[k]))FLEET[k]={modelo:"MI-17",numeroSerie:"",cola:k,components:FLEET[k]};if(!FLEET[k].components)FLEET[k].components=[];if(!FLEET[k].cola)FLEET[k].cola=k}}
function recalc(d){d["TSO actual (h)"]=toNum(d["TSO actual (h)"]);d["Recurso asignado"]=toNum(d["Recurso asignado"]);d["Recurso restante"]=toNum(d["Recurso restante"]);d["Arranques TSO"]=d["Arranques TSO"]===""?null:toNum(d["Arranques TSO"]);d["Recurso arranques"]=d["Recurso arranques"]===""?null:toNum(d["Recurso arranques"]);const asignado=d["Recurso asignado"]||d["TSO actual (h)"]+Math.max(0,d["Recurso restante"]);d.DisponiblePct=asignado>0?Math.max(0,Math.min(100,d["Recurso restante"]/asignado*100)):0;d.ConsumidoPct=Math.max(0,Math.min(100,100-d.DisponiblePct));d["% Disponible"]=d.DisponiblePct/100;d["Días restantes calendario"]=daysUntil(d["Vencimiento Fecha"]);const starts=d["Arranques TSO"]&&d["Recurso arranques"]&&d["Arranques TSO"]>d["Recurso arranques"];d["Exceso arranques"]=starts?d["Arranques TSO"]-d["Recurso arranques"]:null;d["Requiere Overhaul"]=(d["Recurso restante"]<=0||starts)?"SI":"NO";d.Criticidad=d["Requiere Overhaul"]==="SI"?"Crítico":(d.DisponiblePct<=30?"Precaución":"Normal");d.Estado=d["Requiere Overhaul"]==="SI"?"OVERHAUL REQUERIDO":(d.Estado==="PENDIENTE"?"PENDIENTE":"OPERATIVO")}
function aircraft(){if(!FLEET[currentAircraft]) currentAircraft=Object.keys(FLEET)[0]||"PNP-503";return FLEET[currentAircraft]}
function data(){const a=aircraft();a.components.forEach(recalc);return a.components}
function statusClass(d){return d.Criticidad==="Crítico"?"crit":d.Criticidad==="Precaución"?"warn":"ok"}
function isMainComponent(name){return /motor|reductor/i.test(name||"")}
function filtered(){let arr=data().filter(d=>mode==="todos"||isMainComponent(d.Componente));const sort=$("sort").value;return [...arr].sort((a,b)=>sort==="recurso"?(a["Recurso restante"]??999999)-(b["Recurso restante"]??999999):sort==="disponible"?(a.DisponiblePct??0)-(b.DisponiblePct??0):sort==="vencimiento"?(a["Días restantes calendario"]??999999)-(b["Días restantes calendario"]??999999):sort==="estado"?String(a.Estado).localeCompare(String(b.Estado)):0)}
function inputFor(i,field,val){const numeric=["TSO actual (h)","Recurso asignado","Recurso restante","Arranques TSO","Recurso arranques"].includes(field);return `<input class="edit-input long" ${numeric?"type='number' step='0.01'":"type='text'"} value="${esc(val)}" data-index="${i}" data-field="${esc(field)}">`}
async function audit(action, detail){ if(!currentUser) return; try{ await addDoc(collection(db,'users',currentUser.uid,'audit'),{action,detail,user:currentUser.email,createdAt:serverTimestamp()}); }catch(e){} }
async function saveNow(action='guardar cambios'){ if(!currentUser) return; $('syncStatus').textContent='Guardando...'; normalizeFleet(); const ref=doc(db,'users',currentUser.uid,'dashboard','main'); await setDoc(ref,{fleet:FLEET,currentAircraft,updatedAt:serverTimestamp(),updatedBy:currentUser.email},{merge:true}); localStorage.setItem('backup_fleet',JSON.stringify({FLEET,currentAircraft})); $('syncStatus').textContent='Guardado en Firestore'; await audit(action,{aircraft:currentAircraft}); }
function autosave(action='auto guardado'){ clearTimeout(saveTimer); saveTimer=setTimeout(()=>saveNow(action).catch(e=>alert('Error Firestore: '+e.message)),700); }
function updateField(i,field,value,rerender=false){const d=data()[i];d[field]=["TSO actual (h)","Recurso asignado","Recurso restante","Arranques TSO","Recurso arranques"].includes(field)?(value===""?"":toNum(value)):value;recalc(d);autosave(`editar ${field}`);if(rerender)render()}
function deleteComponent(i){const comp=data()[i];if(confirm(`¿Eliminar componente ${comp.Componente}?`)){aircraft().components.splice(i,1);autosave('eliminar componente');render()}}
function renderAircraftList(){const list=$("aircraftList");list.innerHTML=Object.keys(FLEET).map(k=>`<button class="aircraft-btn ${k===currentAircraft?'active':''}" data-aircraft="${esc(k)}"><b>${esc(FLEET[k].cola||k)}</b><small>Modelo: ${esc(FLEET[k].modelo||'—')} · Serie: ${esc(FLEET[k].numeroSerie||'—')} · ${FLEET[k].components.length} componente(s)</small></button>`).join("");list.querySelectorAll('.aircraft-btn').forEach(b=>b.addEventListener('click',()=>{currentAircraft=b.dataset.aircraft;autosave('cambiar aeronave');closeDrawer();render()}))}
function renderKpis(arr){const total=arr.length,oper=arr.filter(d=>d.Estado==="OPERATIVO").length,min=[...arr].sort((a,b)=>(a["Recurso restante"]??999999)-(b["Recurso restante"]??999999))[0]||{};const k=[["Aeronave",aircraft().cola||currentAircraft,aircraft().modelo||"—"],["Componentes",total,"Elementos mostrados"],["Operativos",oper,`${total?Math.round(oper/total*100):0}% de la selección`],["Menor recurso",`${fmt(min["Recurso restante"],1)} h`,min.Componente||"—"]];$("kpis").innerHTML=k.map(x=>`<div class="panel kpi"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="hint">${x[2]}</div></div>`).join("")}
function renderCards(arr){const all=data();$("cards").innerHTML=arr.map(d=>{const i=all.indexOf(d);return `<article class="panel component-card ${statusClass(d)}"><div class="card-title"><h3>${esc(d.Componente)}</h3><div class="card-actions"><span class="pill ${statusClass(d)}">${d.Estado}</span><button class="deleteBtn del-component" data-index="${i}">Eliminar</button></div></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,d.DisponiblePct))}%"></i></div><div class="small">${fmt(d.DisponiblePct,1)}% disponible · ${fmt(d.ConsumidoPct,1)}% consumido</div><div class="meta" style="margin-top:12px">${EDITABLE_FIELDS.map(f=>`<div class="field"><label>${f}</label>${inputFor(i,f,d[f])}</div>`).join("")}</div></article>`}).join("");document.querySelectorAll('.del-component').forEach(b=>b.addEventListener('click',()=>deleteComponent(+b.dataset.index)))}
function drawBar(arr){const c=$("barChart"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);const h=c.height-80,max=Math.max(...arr.map(d=>Math.max(d["TSO actual (h)"]||0,d["Recurso restante"]||0)),1500);ctx.font="14px Segoe UI";ctx.fillStyle="#a9bbd2";ctx.fillText("Horas",18,24);arr.forEach((d,i)=>{const y=55+i*(h/Math.max(1,arr.length))+14,x0=160,bw=c.width-270;ctx.fillStyle="#edf5ff";ctx.fillText(String(d.Componente).slice(0,18),12,y+10);ctx.fillStyle="rgba(255,255,255,.10)";ctx.fillRect(x0,y-4,bw,14);ctx.fillStyle="#38bdf8";ctx.fillRect(x0,y-4,bw*((d["TSO actual (h)"]||0)/max),14);ctx.fillStyle="rgba(255,255,255,.10)";ctx.fillRect(x0,y+18,bw,14);ctx.fillStyle=statusClass(d)==="crit"?"#ef4444":"#22c55e";ctx.fillRect(x0,y+18,bw*(Math.max(0,d["Recurso restante"]||0)/max),14);ctx.fillStyle="#cfe6ff";ctx.fillText(`TSO ${fmt(d["TSO actual (h)"],1)} h`,x0+bw+10,y+8);ctx.fillText(`Rest. ${fmt(d["Recurso restante"],1)} h`,x0+bw+10,y+30)})}
function drawDonut(arr){const c=$("donutChart"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);const avg=arr.reduce((s,d)=>s+(d.DisponiblePct||0),0)/Math.max(1,arr.length),cx=c.width/2,cy=160,r=105;ctx.lineWidth=34;ctx.strokeStyle="rgba(255,255,255,.10)";ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=avg>30?"#22c55e":avg>10?"#f59e0b":"#ef4444";ctx.beginPath();ctx.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*(avg/100));ctx.stroke();ctx.fillStyle="#edf5ff";ctx.font="bold 42px Segoe UI";ctx.textAlign="center";ctx.fillText(`${fmt(avg,1)}%`,cx,cy+10);ctx.font="14px Segoe UI";ctx.fillStyle="#a9bbd2";ctx.fillText("promedio disponible",cx,cy+36);$("donutText").textContent=`Promedio calculado sobre ${arr.length} componente(s) visibles.`}
function renderTable(arr){const all=data(),cols=[...EDITABLE_FIELDS,"DisponiblePct","Estado","Requiere Overhaul"];$('dataTable').innerHTML=`<thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>`+arr.map(d=>{const i=all.indexOf(d);return `<tr>${cols.map(c=>{let v=EDITABLE_FIELDS.includes(c)?inputFor(i,c,d[c]):(c==="DisponiblePct"?fmt(d[c],1)+"%":d[c]);return `<td data-label="${esc(c)}">${v??""}</td>`}).join('')}</tr>`}).join('')+'</tbody>'}
function renderAlerts(arr){const out=[];arr.forEach(d=>{if(d["Requiere Overhaul"]==="SI")out.push(`🔴 <b>${esc(d.Componente)}</b>: requiere Overhaul. Estado: ${d.Estado}.`);if((d.DisponiblePct||0)<=30&&d["Requiere Overhaul"]!=="SI")out.push(`🟡 <b>${esc(d.Componente)}</b>: disponibilidad baja (${fmt(d.DisponiblePct,1)}%).`);if(d["Exceso arranques"])out.push(`🔴 <b>${esc(d.Componente)}</b>: excede arranques por ${d["Exceso arranques"]}.`)});if(!out.length)out.push(`🟢 ${esc(aircraft().cola)}: componentes visibles operativos.`);$('alerts').innerHTML=out.map(a=>`<div class="alert" style="margin:8px 0">${a}</div>`).join('')}
function render(){normalizeFleet();const a=aircraft();$('topTitle').textContent=a.cola||currentAircraft;$('mainTitle').textContent=`Dashboard editable ${a.cola||currentAircraft}`;$('mainSubtitle').textContent=`Modelo ${a.modelo||'—'} · N° serie ${a.numeroSerie||'—'} · Control de componentes, TSO, recurso, taller y Overhaul.`;$('airModel').value=a.modelo||'';$('airSerial').value=a.numeroSerie||'';$('airTail').value=a.cola||currentAircraft;$('updatedAt').textContent=new Date().toLocaleDateString('es-PE');renderAircraftList();const arr=filtered();renderKpis(arr);renderCards(arr);drawBar(arr);drawDonut(arr);renderTable(arr);renderAlerts(arr)}
function addComponent(){const name=prompt('Nombre del componente (ej: Motor 3, Reductor, AI-9B, Bomba hidráulica):');if(!name)return;aircraft().components.push({Componente:name,Modelo:'',"N° Serie":'',Taller:'',"Último Overhaul Fecha":'',"TSO actual (h)":0,"Recurso asignado":0,"Recurso restante":0,"Tiempo de servicio":'',"Vencimiento Fecha":'',Estado:'PENDIENTE',"Arranques TSO":null,"Recurso arranques":null,"Exceso arranques":null});autosave('agregar componente');render()}
function createAircraft(){let tail=$('newTail').value.trim();const modelo=$('newModel').value.trim(),serie=$('newSerial').value.trim();if(!tail){alert('Escribe el número de cola. Ejemplo: PNP-504');return}tail=tail.toUpperCase();if(FLEET[tail]){alert('Esa aeronave ya existe.');return}FLEET[tail]={modelo,numeroSerie:serie,cola:tail,components:[]};currentAircraft=tail;autosave('crear aeronave');$('newTail').value='';$('newModel').value='';$('newSerial').value='';render();alert('Aeronave creada. Ahora puedes agregar sus componentes.')}
function deleteAircraft(){if(Object.keys(FLEET).length<=1){alert('Debe quedar al menos una aeronave.');return}if(confirm(`¿Eliminar aeronave ${aircraft().cola}?`)){delete FLEET[currentAircraft];currentAircraft=Object.keys(FLEET)[0];autosave('eliminar aeronave');render()}}
function exportExcel(){const a=aircraft(),rows=data();const cols=["Componente","Modelo","N° Serie","Taller","Último Overhaul Fecha","TSO actual (h)","Recurso asignado","Recurso restante","DisponiblePct","Tiempo de servicio","Vencimiento Fecha","Estado","Requiere Overhaul","Arranques TSO","Recurso arranques","Exceso arranques"];let html=`<html><head><meta charset='UTF-8'><style>table{border-collapse:collapse;font-family:Calibri}th{background:#1f4e78;color:white;font-weight:bold}td,th{border:1px solid #9e9e9e;padding:8px} .title{font-size:20px;font-weight:bold;background:#d9ead3}.sub{background:#ddebf7;font-weight:bold}</style></head><body><table><tr><td class='title' colspan='${cols.length}'>Dashboard de componentes - ${esc(a.cola)}</td></tr><tr><td class='sub'>Modelo aeronave</td><td>${esc(a.modelo)}</td><td class='sub'>N° Serie aeronave</td><td>${esc(a.numeroSerie)}</td><td class='sub'>Número de cola</td><td>${esc(a.cola)}</td></tr><tr></tr><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='DisponiblePct'?fmt(r[c],1)+'%':esc(r[c]??'')}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const blob=new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8;'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`componentes_${a.cola}.xls`;link.click();URL.revokeObjectURL(url)}
function openDrawer(){$('drawer').classList.add('open');$('drawerBackdrop').classList.add('open')}
function closeDrawer(){$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('open')}
async function loadDashboard(user){ currentUser=user; $('userEmail').textContent=user.email; const ref=doc(db,'users',user.uid,'dashboard','main'); const snap=await getDoc(ref); if(snap.exists()){ const d=snap.data(); FLEET=d.fleet||structuredClone(DEFAULT_FLEET); currentAircraft=d.currentAircraft||Object.keys(FLEET)[0]||'PNP-503'; } else { FLEET=structuredClone(DEFAULT_FLEET); currentAircraft='PNP-503'; await saveNow('crear dashboard inicial'); } normalizeFleet(); render(); }
function bindEvents(){
  $('loginBtn').addEventListener('click',()=>signInWithEmailAndPassword(auth,$('authEmail').value,$('authPassword').value).catch(e=>showMsg(e.message)));
  $('registerBtn').addEventListener('click',()=>createUserWithEmailAndPassword(auth,$('authEmail').value,$('authPassword').value).catch(e=>showMsg(e.message)));
  $('logoutBtn').addEventListener('click',()=>signOut(auth));
  document.addEventListener('change',e=>{if(e.target.classList.contains('edit-input')&&e.target.dataset.field)updateField(+e.target.dataset.index,e.target.dataset.field,e.target.value,true)});
  document.addEventListener('blur',e=>{if(e.target.classList.contains('edit-input')&&e.target.dataset.field)updateField(+e.target.dataset.index,e.target.dataset.field,e.target.value,true)},true);
  document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');mode=btn.dataset.mode;render()}));
  $('sort').addEventListener('change',render);$('saveData').addEventListener('click',()=>saveNow().then(()=>alert('Cambios guardados')));$('resetData').addEventListener('click',()=>{if(confirm('¿Restaurar todos los datos de ejemplo?')){FLEET=structuredClone(DEFAULT_FLEET);currentAircraft='PNP-503';autosave('restaurar datos');render()}});$('addComponent').addEventListener('click',addComponent);$('createAircraft').addEventListener('click',createAircraft);$('deleteAircraft').addEventListener('click',deleteAircraft);$('exportExcel').addEventListener('click',exportExcel);document.querySelectorAll('.aircraft-field').forEach(inp=>inp.addEventListener('change',e=>{aircraft()[e.target.dataset.airfield]=e.target.value.trim();if(e.target.dataset.airfield==='cola'){const old=currentAircraft,newKey=e.target.value.trim().toUpperCase()||old;if(newKey!==old&&!FLEET[newKey]){FLEET[newKey]=FLEET[old];delete FLEET[old];currentAircraft=newKey}aircraft().cola=newKey}autosave('editar datos aeronave');render()}));$('openDrawer').addEventListener('click',openDrawer);$('closeDrawer').addEventListener('click',closeDrawer);$('drawerBackdrop').addEventListener('click',closeDrawer);
}
bindEvents();
onAuthStateChanged(auth, user=>{ if(user){ $('authView').classList.add('hidden'); $('appView').classList.remove('hidden'); loadDashboard(user).catch(e=>alert('Error al cargar Firestore: '+e.message)); } else { currentUser=null; $('appView').classList.add('hidden'); $('authView').classList.remove('hidden'); }});
